omic_meta_data:
  /home/exacloud/lustre1/CEDAR/roskamsh/projects/Omics-QC-pipeline/data/PP_cohort_sample_info_log_JE.2018.09.28.txt
base_dir:
  /home/exacloud/lustre1/CEDAR/roskamsh/projects/Omics-QC-pipeline
gtf_file:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/gencode.v27.annotation.gtf
bed_file:
  /home/exacloud/lustre1/CEDAR/roskamsh/projects/Omics-QC-pipeline/data/gencode_v27.bed
exon_gtf:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/gencode.housekeeping_genes.exon.gtf
adapter-PE:
  /home/exacloud/lustre1/CEDAR/roskamsh/projects/Omics-QC-pipeline/data/TruSeq2-PE.fa
adapter-SE:
  /home/exacloud/lustre1/CEDAR/roskamsh/projects/Omics-QC-pipeline/data/TruSeq2-SE.fa
#path to tools
star_tool:
  /home/exacloud/lustre1/CEDAR/tools/STAR/tags/2.5.3a/bin/Linux_x86_64/STAR
picard_tool:
  /home/exacloud/lustre1/CEDAR/tools/picard-tools-1.119/MarkDuplicates.jar
genome:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/GRCh38.primary_assembly.genome.fa
refflat2:
  /home/exacloud/lustre1/CEDAR/Genomes/gencode27_refflat2.txt
star_index:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/
project_id:
  cfRNA_11_01
baseline:
  HD
linear_model:
  Type
seq_layout:
  PE
sample_id:
  StudyID
dds_design:
  SampleID
rseqc_env:
  source activate rseqc-omic-wf
meta_columns_to_plot:
  Type: Type
  Notes: Notes
  RNA_extraction_date: RNA_extraction_date
diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    HD-vs-MM:
      - HD
      - MM
    HD-vs-LG:
      - HD
      - LG
pca:
  labels:
    # columns of sample sheet to use for PCA
    - Type
# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: /home/exacloud/lustre1/CEDAR/roskamsh/projects/Omics-QC-pipeline/data/PP_cohort_sample_info_log_JE.2018.09.28.txt
