

omic_meta_data:
  /home/exacloud/lustre1/CompBio/estabroj/CEDAR/cfrna/data/first_round_sequencing/PP_cohort_sample_info_log_JE.2018.06.06.txt

base_dir:
  /home/exacloud/lustre1/CompBio/estabroj/CEDAR/practice_snakmake

gtf_file:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/gencode.v27.annotation.gtf

bed_file:
  /home/exacloud/lustre1/CompBio/estabroj/CEDAR/practice_snakmake/gencode_v27.bed

fastq_dir:
  /home/exacloud/lustre1/CEDAR/cfrna/data/LIB180515JW

project_id:
  CFRNA_7_2_18

baseline:
  HD

linear_model:
  Type

seq_layout:
  PE

sample_id:
  StudyID

dds_design:
  SampleID

rseqc_env:
  source activate rseqc-omic-wf

meta_columns_to_plot:
  Type: Type
  Notes: Notes
  RNA_extraction_date: RNA_extraction_date

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    HD-vs-LG:
      - HD
      - LG
    HD-vs-LCir:
      - HD
      - LCir
    HD-vs-MG:
      - HD
      - MG
    HD-vs-MM:
      - HD
      - MM
    HD-vs-LCx:
      - HD
      - LCx
    HD-vs-CR:
      - HD
      - CR

pca:
  labels:
    # columns of sample sheet to use for PCA
    - Type

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: /home/exacloud/lustre1/CompBio/estabroj/CEDAR/cfrna/data/first_round_sequencing/PP_cohort_sample_info_log_JE.2018.06.06.txt
