#path to samples files, in tab delimited format, with columns sample name, path to fq1 file, path to fq2 file


omic_counts_data:
  /home/exacloud/lustre1/CEDAR/cfrna/analysis/pancan_omic_qc/data/cfrna_joined_counts_samps_1-48_6-8-18.txt

omic_meta_data:
  /home/exacloud/lustre1/CEDAR/cfrna/analysis/pancan_omic_qc/PP_cohort_sample_info_log_JE.2018.06.06.txt

omic_qc_results:
  /home/users/estabroj/CEDAR/cfrna/analysis/pancan_omic_qc/results

project_id:
  cfrna_6_10_18

baseline:
  HD

linear_model:
  Type

sample_id:
  StudyID

meta_columns_to_plot:
  Type,Notes,RNA_extraction_date
