

omic_meta_data:
  /home/exacloud/lustre1/CEDAR/cfrna/analysis/pancan_omic_qc/PP_cohort_sample_info_log_JE.2018.06.06.txt

base_dir:
  /home/exacloud/lustre1/CompBio/estabroj/CEDAR/practice_snakmake

project_id:
  cfrna_joined_counts_samps_1-48_6-8-18

baseline:
  HD

linear_model:
  Type

sample_id:
  StudyID

meta_columns_to_plot:
  Type: Type
  Notes: Notes
  RNA_extraction_date: RNA_extraction_date
