

omic_meta_data:
  /home/exacloud/lustre1/CompBio/estabroj/CEDAR/cfrna/data/first_round_sequencing/PP_cohort_sample_info_log_JE.2018.06.06.txt

base_dir:
  /home/exacloud/lustre1/CompBio/estabroj/CEDAR/practice_snakmake

gtf_file:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/gencode.v27.annotation.gtf

bed_file:
  /home/exacloud/lustre1/CompBio/estabroj/CEDAR/practice_snakmake/gencode_v27.bed

project_id:
  test_rseqc

baseline:
  HD

linear_model:
  Type

seq_layout:
  PE

sample_id:
  StudyID

rseqc_env:
  source activate rseqc-omic-wf

meta_columns_to_plot:
  Type: Type
  Notes: Notes
  RNA_extraction_date: RNA_extraction_date

diffexp:
  contrasts:
    healthy-vs-LG:
      - HD
      - LG

pca:
  labels:
    - Type

